# Generated by Django 4.2.2 on 2023-06-16 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prato',
            name='date_prato',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
