# Generated by Django 4.2.2 on 2023-06-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0002_alter_prato_date_prato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prato',
            options={'verbose_name': 'Prato', 'verbose_name_plural': 'Pratos'},
        ),
    ]
